[package]
name = "mouser_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { workspace = true }
egui = { workspace = true }
tray-icon = { workspace = true }
image = { workspace = true, features = ["png", "webp"] }
dirs = { workspace = true }
ureq = { workspace = true }
sha2 = { workspace = true }
serde = { workspace = true }
mouser_engine = { path = "../engine" }
log = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = { workspace = true }
