[package]
name = "mouser-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
hidapi = { workspace = true }
evdev = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
flexi_logger = { workspace = true }
nix = { workspace = true }
dirs = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }
tray-icon = { workspace = true }
engine = { package = "mouser_engine", path = "../engine" }
gui = { package = "mouser_gui", path = "../gui" }
tokio = { workspace = true }
async-trait = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = { workspace = true }
